### ISSUE TITLE
Issues with multiple git tags on one commit

### ISSUE THREAD

**Issue by grawlinson** [anse1/sqlsmith#46]
https://github.com/anse1/sqlsmith/blob/0547f1e2f27755a6066f48445ed4c1ca54734718/Makefile.am#L33-L38

1.3 currently has two tags on the same commit `v1.3` and `debian/1.3-1`.

When compiling from source with git, the version output shows the wrong tag.

```sh
$ sqlsmith --version
SQLsmith debian/1.3-1
```

I suggest stop using the weird debian tags and let debian use normal tags like everyone else.

**Comment by grawlinson** [comment]
I've fixed this by patching in an exclude flag:

```sh
sed -i "s/git describe/git describe --exclude='debian*'/" Makefile
```

Re-reading my original comment, I think it may come across as hostile, that was not my intention. I apologise for that.

**Comment by anse1** [comment]
George Rawlinson writes:
> sed -i "s/git describe/git describe --exclude='debian*'/" Makefile

Thanks, I'll update the CMake build similarly.

> Re-reading my original comment, I think it may come across as hostile,
> that was not my intention. I apologise for that.

I appreciate your clarification.  And yes, people have warned me earlier
that the whole "grab release or hash from git" is a bad idea, and it is
beginning to dawn on me as well now since issues with new ways it can
break don't appear to dry up :-)

Thanks,
andreas
